apiVersion: kustomize.toolkit.io/v1
kind: Kustomization
metadata:
  name: devops-app-production
spec:
  path: app/base/
  patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: dockrphage/devops-app:latest
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: v1.0.0-prod
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ENVIRONMENT
          value: production
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1000m"
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/initialDelaySeconds
        value: 30
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/initialDelaySeconds
        value: 10
    target:
      kind: Deployment
      name: devops-app
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: devops-app-prod.local
    target:
      kind: Ingress
      name: devops-app-ingress
